---
title: "."
output: 
  flexdashboard::flex_dashboard:
    logo: fig/hex-tidyverse.png
    orientation: rows    
    theme: readable
    vertical_layout: fill
    css: extra.css
    include:
      after_body: footer.html
      before_body: header.html
mainfont: NanumGothic 
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
## 0. R 마크다운 환경설정 ------
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

options(knitr.duplicate.label = 'allow')

library(flexdashboard)
```


Code of Conduct
===============================================================================

**행동 강령 (Code of Conduct)**:

<br>

네트워킹과 협업 그리고 학습을 위해서 공동체 행사의 일환으로 서울 R 미트업이 기획되었다. 과학 공동체에 속한 모든 구성원의 참여를 중시하고, 참석자 모두가 즐겁고 성취감을 얻어갔으면 합니다. 따라서, 모든 참여자는 워크샵 동안에 다른 참석자에 대한 존경과 예의를 보여주셔야 합니다.

<br>

좀더 명확히 하기 위해서, 서울 R 미트업와 토론에 참여한 모든 사람 - 강사, 조교, 학습자, 주최자 - 은 다음 행동 강령(code of conduct)을 지켜야 합니다. 미트업 주최측에서는 행사동안에 행동 강령을 적용해야 합니다.

<br>

성별, 동성애, 장애, 외모, 신체 크기, 인종, 국적, 종교 혹은 텍스트 편집기 선택에 관계없이, 괴롭힘 없는 학습 경험을 제공하는데 최선을 다하고 있습니다. 어떤 형태로 참가자를 괴롭히거나 희롱하는 것을 용납하지 않을 것입니다.

<br>

괴롭힘과 희롱에는 성별, 동성애, 장애, 외모, 신체 크기, 인종, 국적, 종교와 관계된 공격적인 언급 및 공공 장소에서 성적 이미지, 고의적인 위협, 스토킹, 희롱하는 사진이나 녹음, 지속적인 대화나 행사 중단, 부적절한 신체 접촉, 불쾌한 성적 관심도 포함합니다.
다양한 배경의 사람들을 포함하는 전문 참가자에게 모든 의사소통이 적절해야 한다. 성적 언어와 이미지는 어떤 경우에도 적절하지 않습니다.
다른 사람들에게 친절해야 합니다. 다른 참석자를 모욕하거나 폄하하지 마세요.
전문가 프로처럼 행동하세요. 성희롱과 성차별, 인종차별, 배제하는 농담은 적절하지 않습니다.
괴롭히거나 희롱하는 행동을 멈추도록 주의받은 참여자는 즉시 행동강령을 준수해야 합니다. 이러한 규칙을 위반한 참가자는 돌려받을 수도 있는 학습비의 환불없이 주최측의 재량에 따라 행사를 떠나도록 요청받을 수도 있습니다.

<br>

모든 사람을 위해서 따뜻하고 친목을 도모할 수 있는 미트업을 만들수 있도록 도와주셔서 감사합니다.


