---
title: "."
output: 
  flexdashboard::flex_dashboard:
    logo: fig/hex-tidyverse.png
    orientation: rows    
    theme: readable
    vertical_layout: fill
    css: extra.css
    include:
      after_body: footer.html
      before_body: header.html
mainfont: NanumGothic 
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
## 0. R 마크다운 환경설정 ------
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

options(knitr.duplicate.label = 'allow')

library(flexdashboard)
```


2020
===============================================================================


Column {.tabset}
-----------------------------------------------------------------------------

### Overview

<br>
<br>

- When: **Wednesday, November 11, 2020 7:00 PM to 9:00 PM GMT+9**
    - RSVP opens **RSVP opens Wednesday, October 28, 2020 7:00 PM**
- Where: Online Event - Link visible for attendees
- [Seoul R Users: 2020 - November](https://www.meetup.com/seoul-r-meetup/events/rmcgxrybcpbpb/)

<br>
<br>

- **Schedule**
    - 6:30 open zoom
    - 7:00-7:30 Presentation Talk 1
    - 7:30-8:00 Presentation Talk 2
    - 8:00-8:30 Presentation Talk 3
    - 8:30 ~ 9:00 Virtual Social

<br>
<br>


### September (9월)

<br>
<br>

- When: **Wednesday, September 9, 2020 7:00 PM to 9:00 PM GMT+9 **
    - RSVP opens **Wednesday, August 26, 2020** 7:00 PM
- Where: Online Event - Link visible for attendees
- [Seoul R Users: 2020-September](https://www.meetup.com/seoul-r-meetup/events/wpltwrybcmbmb/)

<br>
<br>

- **Talk** (25min talk, 5min Q&A)
    - Title: Why Tidymodels
    - Korean Title: 왜 당근(caret)은 안되고 새로운 신상 당근(Tidymodel)인가?
    - **Speaker**: Kwangchun Lee (이광춘)
    - [slide deck](https://statkclee.github.io/ds-authoring/ds-why-tidymodels.html#/)
    - Abstract: Tidyverse is regareded as a new framework, ecosystem, thought leader for data science. Tidyverse also has a profound effect on models. When Max Kun moved to RStudio, perhaps the Tidymodels has begun. Now Tidymodels have become the standard of ML.
    - 초록: Tidyverse는 데이터 과학을 위한 새로운 프레임워크, 생태계, 리더로 받아들여지고 있다. ML 분야도 Tidyverse 영향을 벗어날 수 없었다. Max Khun 박사가 RStudio로 자리를 옮기는 시점부터 아마도 Tidymodels의 시작으로 볼 수 있고 몇년이 지나 Tidymodels는 ML 의 표준으로 자리잡아가고 있다.
- **Talk** (25min talk, 5min Q&A)
    - Title: "MLOps with R: Collaboration of data scientists & developers/engineers"
    - Korean Title: "R에서 MLOps 시작하기: 데이터 과학자 & 개발자/엔지니어 협력"
    - **Speaker**: Ian Choi (최영락)
    - Abstract: Machine Learning Operations (MLOps) process becomes critical for reliable and efficient deployment of applications that depend on R-based models. This talk explains and demonstrates MLOps from DevOps story by dividing into three R components: 1) data upload, 2) machine learning model training & deployment, and 3) visualization with Shiny with Azure Machine Learning Service and GitHub Actions.
    - 초록: 한글: R 기반 모델로 만들어진 데이터 분석 & 머신 러닝 모델을 안정적이고 효율적으로 지속적인 배포를 위해서는 MLOps프로세스가 필수일 것입니다. 본 발표에서는 DevOps에 대한 이야기를 시작으로, R로 구현한 1) 데이터 업로드 2) 머신 러닝 모델 트레이닝 & 배포 3) 시각화 분석 활용 (Shiny) 이라는 3가지 파트가 Azure Machine Learning Service와 GitHub Actions을 통해 MLOps를 데모와 함께 살펴봅니다.
    - [slide deck](https://aka.ms/ian-mlops-r)
- **Talk** (25min talk, 5min Q&A)
    - Title: The awesome way to buy a good calf with data science.
    - Korean Title: 데이터 과학과 함께 좋은 송아지를 사는 방법
    - **Speaker**: Youngjun Na (나영준)
    - [slide deck](data/나영준-SeoulR.pdf)

### October (10월)

<br>
<br>


- **Talk** (25min talk, 5min Q&A)
    - Title: Weather Report Automation - GitHub Actions
    - Korean Title: "날씨보고서 자동화 - GitHub Actions"
    - **Speaker**: Kwangchun Lee (이광춘)
    - [slide deck](https://statkclee.github.io/ds-authoring/ds-weather-github-actions.html)
    - Abstract: Automation can a valuable asset for every data scientist. Through newly introduced GitHub Actions many repetitive data science works can be automated such that data scientists can spend more time on problem solvings. Motivated Python weather alerts app, automating weather report has been demonstrated. Meanwhile Xaringan and friends have shown new breakthrough for making slideshows impressive!!!
    - 초록: 자동화는 모든 데이터 과학자에게 정말 중요한 자산이 된다. 새로 소개된 Github Actions을 통해 반복되는 많은 작업을 자동화시킴으로써 본질적인 문제를 해결하는데 더 많은 시간을 쓸 수 있을 것으로 기대된다. 파이썬 날씨 알리미 앱에 영감을 받아 날씨 보고서 자동생성 사례를 시연한다. Xaringan과 친구들로 새로 제작된 발표자료는 감명깊은 발표자료를 제작하는데 큰 영향을 줄 것으로도 기대된다.
- **Talk** (25min talk, 5min Q&A)
    - Title: "Tidy하게 그리고 Seamless하게"
    - Korean Title: "Tidy하게 그리고 Seamless하게"
    - **Speaker**: Choonghyun Ryu (유충현)
    - [slide deck](https://github.com/choonghyunryu/R_Materials/tree/master/Meetup/Tidyverse_Korea/Seamless_in_R)
    - 초록: 통계학자에서 비롯된 R 생태계가 이제는 Software Engineer의 합류로 더욱더 풍성해지고 있다. R의 태동과 진화의 역사로부터 tidy하고 seamless한 데이터 분석 아키텍트의 진화에 대해 소개한다. 그리고 이를 응용한 사례에 대한 소개와 tidy하고 seamless한 데이터분석 접근방법에 대해서 논의한다.
- **Talk** (25min talk, 5min Q&A)
    - Title: A/B 테스트와 Multi-Armed Bandit
    - Korean Title: A/B Testing & Multi-Armed Bandit
    - **Speaker**: Sulgi Kim (김설기)
    - [slide deck](data/MAB_RMeetUp.pptx)
    - 초록: AI 와 ML 은 과거의 offline / history 데이터만 이용하는 경우가 많지만, 이는 온라인 상에서 비교/확인을 하지 않는다는 점에서 한계가 있다.
이를 극복하기 위해서 A/B 테스트로 대표되는 온라인 테스트와 함께 쓰여야 한다. 
한편,  multi-armed bandit 이라는 방법은 A/B 테스트보다 유연한 테스트와 실험을 할 수 있게 한다. 
이번 발표에서는 multi-armed bandit 을 소개하고, 활용가능성과 새로운 발견들에 대해 논의한다. 

### November (11월)

<br>
<br>


- **Talk** (25min talk, 5min Q&A)
    - Title: Almost All about Table
    - Korean Title: "표에 대한 거의 모든 것"
    - **Speaker**: Kwangchun Lee (이광춘)
- **Talk** (25min talk, 5min Q&A)
    - Title: "It's just a magic!!!"
    - Korean Title: "유튜브 데이터의 마술"
    - **Speaker**: Kevin Na (나성호)
    - Abstract: 유튜브 크롤링으로 수집한 데이터를 sqlite3로 저장하고 깃허브로 푸쉬할 때마다 자동으로 Shiny 대시보드에서 호출하여 시각화하는 방법을 공유하는 자리입니다. YouTube Crawler + Sqlite DB + Github + RShiny + Crontab = Just Magic!!!
- **Talk** (25min talk, 5min Q&A)
    - Title: "Making serverless API with AWS Lambda and API Gateway in an easy way"
    - Korean Title: "AWS Lamba 와 API Gateway로 가볍게 서버리스 API 만들기"
    - **Speaker**: JungHwan Yun (윤정환)

### December (12월)

<br>
<br>


- **Talk** (25min talk, 5min Q&A)
    - Title: Data Journalism
    - Korean Title: "데이터 저널리즘"
    - **Speaker**: 권오성
- **Talk** (25min talk, 5min Q&A)
    - Title: Simple AutoML Starting with KubeFlow
    - Korean Title: "KubeFlow로 시작하는 간단한 AutoML"
    - **Speaker**: 이승우
- **Talk** (25min talk, 5min Q&A)
    - Title: 
    - Korean Title: 
    - **Speaker**: 
    - Abstract: 


### Janumary (1월)

<br>
<br>


- **Talk** (25min talk, 5min Q&A)
    - Title: 
    - Korean Title: 
    - **Speaker**: 
- **Talk** (25min talk, 5min Q&A)
    - Title: 
    - Korean Title: 
    - **Speaker**: 
- **Talk** (25min talk, 5min Q&A)
    - Title: "Making Mobile App Using Shiny"
    - Korean Title: "Shiny를 이용한 Mobile App 만들기"
    - **Speaker**: Nam-Hyeon Jee (지남현)
    - Abstract: 
