---
title: "."
output: 
  flexdashboard::flex_dashboard:
    logo: fig/hex-tidyverse.png
    orientation: rows    
    theme: readable
    vertical_layout: fill
    css: extra.css
    include:
      after_body: footer.html
      before_body: header.html
mainfont: NanumGothic 
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
## 0. R 마크다운 환경설정 ------
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE,
                    comment="", digits = 3, tidy = FALSE, prompt = FALSE, fig.align = 'center')

knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

options(knitr.duplicate.label = 'allow')

library(flexdashboard)
```


2020
===============================================================================


Column {.tabset}
-----------------------------------------------------------------------------

### Overview

<br>
<br>

- When: **Wednesday, October 14, 2020 7:00 PM to 9:00 PM GMT+9**
    - RSVP opens **RSVP opens Wednesday, September 30, 2020 7:00 PM**
- Where: Online Event - Link visible for attendees
- [Seoul R Users: 2020 - October](https://www.meetup.com/seoul-r-meetup/events/273025689/)

<br>
<br>

- **Schedule**
    - 6:30 open zoom
    - 7:00-7:30 Presentation Talk 1
    - 7:30-8:00 Presentation Talk 2
    - 8:00-8:30 Presentation Talk 3
    - 8:30 ~ 9:00 Virtual Social

<br>
<br>


### September (9월)

<br>
<br>

- When: **Wednesday, September 9, 2020 7:00 PM to 9:00 PM GMT+9 **
    - RSVP opens **Wednesday, August 26, 2020** 7:00 PM
- Where: Online Event - Link visible for attendees
- [Seoul R Users: 2020-September](https://www.meetup.com/seoul-r-meetup/events/wpltwrybcmbmb/)

<br>
<br>

- **Talk** (25min talk, 5min Q&A)
    - Title: Why Tidymodels
    - Korean Title: 왜 당근(caret)은 안되고 새로운 신상 당근(Tidymodel)인가?
    - **Speaker**: Kwangchun Lee (이광춘)
    - [slide deck](https://statkclee.github.io/ds-authoring/ds-why-tidymodels.html#/)
    - Abstract: Tidyverse is regareded as a new framework, ecosystem, thought leader for data science. Tidyverse also has a profound effect on models. When Max Kun moved to RStudio, perhaps the Tidymodels has begun. Now Tidymodels have become the standard of ML.
    - 초록: Tidyverse는 데이터 과학을 위한 새로운 프레임워크, 생태계, 리더로 받아들여지고 있다. ML 분야도 Tidyverse 영향을 벗어날 수 없었다. Max Khun 박사가 RStudio로 자리를 옮기는 시점부터 아마도 Tidymodels의 시작으로 볼 수 있고 몇년이 지나 Tidymodels는 ML 의 표준으로 자리잡아가고 있다.
- **Talk** (25min talk, 5min Q&A)
    - Title: "MLOps with R: Collaboration of data scientists & developers/engineers"
    - Korean Title: "R에서 MLOps 시작하기: 데이터 과학자 & 개발자/엔지니어 협력"
    - **Speaker**: Ian Choi (최영락)
    - Abstract: Machine Learning Operations (MLOps) process becomes critical for reliable and efficient deployment of applications that depend on R-based models. This talk explains and demonstrates MLOps from DevOps story by dividing into three R components: 1) data upload, 2) machine learning model training & deployment, and 3) visualization with Shiny with Azure Machine Learning Service and GitHub Actions.
    - 초록: 한글: R 기반 모델로 만들어진 데이터 분석 & 머신 러닝 모델을 안정적이고 효율적으로 지속적인 배포를 위해서는 MLOps프로세스가 필수일 것입니다. 본 발표에서는 DevOps에 대한 이야기를 시작으로, R로 구현한 1) 데이터 업로드 2) 머신 러닝 모델 트레이닝 & 배포 3) 시각화 분석 활용 (Shiny) 이라는 3가지 파트가 Azure Machine Learning Service와 GitHub Actions을 통해 MLOps를 데모와 함께 살펴봅니다.
    - [slide deck](https://aka.ms/ian-mlops-r)
- **Talk** (25min talk, 5min Q&A)
    - Title: The awesome way to buy a good calf with data science.
    - Korean Title: 데이터 과학과 함께 좋은 송아지를 사는 방법
    - **Speaker**: Youngjun Na (나영준)
    - [slide deck](data/나영준-SeoulR.pdf)

### October (10월)

<br>
<br>


- **Talk** (25min talk, 5min Q&A)
    - Title: Weather Report Automation - GitHub Actions
    - Korean Title: "날씨보고서 자동화 - GitHub Actions"
    - **Speaker**: Kwangchun Lee (이광춘)
- **Talk** (25min talk, 5min Q&A)
    - Title: "Tidy하게 그리고 Seamless하게"
    - Korean Title: "Tidy하게 그리고 Seamless하게"
    - **Speaker**: Choonghyun Ryu (유충현)
- **Talk** (25min talk, 5min Q&A)
    - Title: A/B 테스트와 Multi-Armed Bandit
    - Korean Title: A/B Testing & Multi-Armed Bandit
    - **Speaker**: Sulgi Kim (김설기)


### November (11월)

<br>
<br>


- **Talk** (25min talk, 5min Q&A)
    - Title: Almost All about Table
    - Korean Title: "표에 대한 거의 모든 것"
    - **Speaker**: Kwangchun Lee (이광춘)
- **Talk** (25min talk, 5min Q&A)
    - Title: "It's just a magic!!!"
    - Korean Title: "유튜브 데이터의 마술"
    - **Speaker**: Kevin Na (나성호)
    - Abstract: 유튜브 크롤링으로 수집한 데이터를 sqlite3로 저장하고 깃허브로 푸쉬할 때마다 자동으로 Shiny 대시보드에서 호출하여 시각화하는 방법을 공유하는 자리입니다. YouTube Crawler + Sqlite DB + Github + RShiny + Crontab = Just Magic!!!
- **Talk** (25min talk, 5min Q&A)
    - Title: "Making serverless API with AWS Lambda and API Gateway in an easy way"
    - Korean Title: "AWS Lamba 와 API Gateway로 가볍게 서버리스 API 만들기"
    - **Speaker**: JungHwan Yun (윤정환)

